# Generated by Django 5.2.1 on 2025-05-28 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pixel',
            unique_together=set(),
        ),
    ]
