# Generated by Django 5.2.1 on 2025-05-28 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pixel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixel',
            name='colored_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
