# Generated by Django 5.2.1 on 2025-05-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pixel_colored_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel',
            name='colored_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
