version: '3.8'

services:
  backend:
    build: ./backend
    container_name: pixel_backend
    volumes:
     - ./backend:/app
    ports: 
     - "5000:5000"
    env_file:
      - ./backend/.env
  
  frontend:
    build: ./frontend
    volumes:
     - ./frontend:/app
     - /app/node_modules 
    container_name: pixel_frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true